### ISSUE TITLE
Serve readiness to indicate when the wrapped process is running

### ISSUE THREAD

**Issue by cjyar** [IronCoreLabs/proa#3]
It would be nice to have proa serve a readiness endpoint that would return 200 only while the wrapped process is running. That way, the "n/m" ready column of pod status would be more reflective of reality.

**Comment by BobWall23** [comment]
If wrapped process has a readiness endpoint, proa should allow that process to handle the readiness check.

**Comment by BobWall23** [comment]
If the wrapped container doesn't already have a readiness check, probably don't want to add a web server just to return readiness.
